interface A {
  stringifier DOMString ();
};

interface B {
  stringifier;
};

[Constructor]
interface StudentA {
  attribute unsigned long id;
  stringifier attribute DOMString name;
};

[Constructor]
interface StudentB {
  attribute unsigned long id;
  attribute DOMString? familyName;
  attribute DOMString givenName;

  stringifier DOMString ();
};