module X
{
    exception E
    {
        unsigned short code;
    };

    exception F
    {
        unsigned short code;
    };

    interface Y
    {
        readonly attribute double a;
        readonly attribute double b setraises (F);
        readonly attribute double c getraises (E);
        readonly attribute double d getraises (E) setraises (F);
        attribute double s;
        attribute double t setraises (F);
        attribute double u getraises (E);
        attribute double v getraises (E) setraises (F);
    };
};
