    exception E
    {
        unsigned short code;
    };

    exception F
    {
        unsigned short code;
    };

    interface Y
    {
        readonly attribute double a;
        readonly attribute double b;
        readonly attribute double c;
        readonly attribute double d;
        attribute double s;
        attribute double t;
        attribute double u;
        attribute double v;
    };
