/* bogus usage of Constructor on an attribute */
interface BogusConstructorEAOnAttribute {
  [Constructor] attribute float r;
}; 

/* Valid usage of constructor */
[Constructor,
 Constructor(float radius)]
interface Circle {
  attribute float r;
  attribute float cx;
  attribute float cy;
  readonly attribute float circumference;
};