/* Uses an undefined type */
interface UseUndefinedType {
  attribute UndefinedType att;
};

typedef UseDefinedType TypeDefType;

/* uses a defined type */
interface UseDefinedType {
  attribute UseUndefinedType att;
  attribute TypeDefType att2;
};