/* TreatNullAs only appear on attributes or operations arguments */
[TreatNullAs]
interface BogusTreatNullAsInterface {};

/* TreatNullAs only appear on attributes or operations arguments with DOMString type */
interface BogusTreatNullAsOnNonDOMStringType {
  [TreatNullAs=EmptyString] attribute long counter;
};

/* TreatNullAs requires an argument */
interface BogusTreatNullAsArgument {
  [TreatNullAs] attribute DOMString name;
};

/* TreatNullAs requires EmptyString as argument */
interface BogusTreatNullAsNoArgument {
  [TreatNullAs=EmptString] DOMString bar();
};

/* Valid usage of TreatNullAs */
interface ValidTreatNullAs {
  [TreatNullAs=EmptyString] attribute DOMString onAttribute;
  [TreatNullAs=EmptyString] DOMString onOperation(long bar);
  boolean onOperationArgument([TreatNullAs=EmptyString] in DOMString bar);
};